server:
  port: 8080
  servlet:
    context-path: /identities

spring:
  datasource:
      url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/identity-service?createDatabaseIfNotExist=true
      username: ${MYSQL_ROOT_USERNAME}
      password: ${MYSQL_ROOT_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: true
        delivery.timeout.ms: 120000
        linger.ms: 1
        request.timeout.ms: 30000
    consumer:
      group-id: identity-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.json.trusted.packages: "*"

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: ${VALID_DURATION}
  refreshable-duration: ${REFRESHABLE_DURATION}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  redirect-uri: ${REDIRECT_URI}
  grant-type: ${GRANT_TYPE}

app:
  services:
    debezium:
      connect-url: ${DEBEZIUM_CONNECT_URL}
  rate-limit:
    user-registration:
      limit-for-period: 5
      limit-refresh-period: 1m
    change-password:
      limit-for-period: 3
      limit-refresh-period: 5m
    forgot-password:
      limit-for-period: 3
      limit-refresh-period: 5m
    reset-password:
      limit-for-period: 3
      limit-refresh-period: 5m
    user-management:
      limit-for-period: 20
      limit-refresh-period: 10s
    role-management:
      limit-for-period: 20
      limit-refresh-period: 10s
    login:
      limit-for-period: 10
      limit-refresh-period: 1m
    introspect:
      limit-for-period: 100
      limit-refresh-period: 1m
    logout:
      limit-for-period: 10
      limit-refresh-period: 1m
    refresh-token:
      limit-for-period: 10
      limit-refresh-period: 1m
    outbound-google:
      limit-for-period: 5
      limit-refresh-period: 1m

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      outbound-identity:
        connectTimeout: 10000
        readTimeout: 10000
      outbound-user-client:
        connectTimeout: 10000
        readTimeout: 10000

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        minimum-number-of-calls: 10
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        writable-stack-trace-enabled: false
        ignore-exceptions:
          - com.MyProject.identity.identity_service.exception.AppException
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
    instances: {}
  ratelimiter:
    configs:
      default:
        timeout-duration: 0s
        limit-for-period: 100
        limit-refresh-period: 10s
    instances:
      userRegistration:
        base-config: default
      changePassword:
        base-config: default
      forgotPassword:
        base-config: default
      resetPassword:
        base-config: default
      userManagement:
        base-config: default
      roleManagement:
        base-config: default
      login:
        base-config: default
      introspect:
        base-config: default
      logout:
        base-config: default
      refreshToken:
        base-config: default
      outboundGoogle:
        base-config: default
  retry:
    configs:
      default:
        max-attempts: 2
        wait-duration: 300ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        ignore-exceptions:
          - com.MyProject.identity.identity_service.exception.AppException
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
    instances: {}

management:
  health:
    circuitbreakers:
      enabled: true