server:
  port: 8888

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      routes:
        - id: block-api-internal-identities
          uri: ${IDENTITY_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/api/v1/identities/users/internal/**
          filters:
            - SetStatus=FORBIDDEN
            - StripPrefix=2
        - id: identity-service
          uri: ${IDENTITY_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/api/v1/identities/**
          filters:
            - StripPrefix=2
        - id: block-api-internal-profiles
          uri: ${PROFILE_SERVICE_URL:http://localhost:8081} 
          predicates:
            - Path=/api/v1/profiles/internal/**
          filters:
            - SetStatus=FORBIDDEN
            - StripPrefix=2
        - id: profile-service
          uri: ${PROFILE_SERVICE_URL:http://localhost:8081} 
          predicates:
            - Path=/api/v1/profiles/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=2
        - id: post-service
          uri: ${POST_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
        - id: file-service
          uri: ${FILE_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/files/**
          filters:
            - StripPrefix=2
        - id: weather-service
          uri: ${WEATHER_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/v1/weathers/**
          filters:
            - StripPrefix=2
        - id: chat-service
          uri: ${CHAT_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/v1/chats/**
          filters:
            - StripPrefix=2
        - id: friend-service
          uri: ${FRIEND_SERVICE_URL:http://localhost:8087}
          predicates:
            - Path=/api/v1/friends/**
          filters:
            - StripPrefix=2
        - id: socket-service
          uri: ${SOCKET_SERVICE_URL:http://localhost:8088}
          predicates:
            - Path=/api/v1/sockets/**
          filters:
            - StripPrefix=2
        - id: comment-service
          uri: ${COMMENT_SERVICE_URL:http://localhost:8089}
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - StripPrefix=2
        - id: film-service
          uri: ${FILM_SERVICE_URL:http://localhost:8090}
          predicates:
            - Path=/api/v1/films/**
          filters:
            - StripPrefix=2

jwt:
  signerKey: ${JWT_SIGNER_KEY}


