server:
  port: 8085
  servlet:
    context-path: /weather

jwt:
  signerKey: ${JWT_SIGNER_KEY:uahkQQArjCd/s458SRMXBYTBbV8FiePF7TPREMKeRijTgiD6DOkEdtmxtcGPVGP0}

app:
  service:
    url:
      weather-client: "https://api.openweathermap.org"

open-weather-map:
  api-key: ${WEATHER_API_KEY:7a1fa87d35a45bdf79db80f19f4f3c56}
  lang: "en"
  units: "metric"