server:
  port: 8083
  servlet:
    context-path: /post

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://root:REDACTED_LEGACY_CREDENTIAL@localhost:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: post-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

jwt:
  signerKey: "uahkQQArjCd/s458SRMXBYTBbV8FiePF7TPREMKeRijTgiD6DOkEdtmxtcGPVGP0"
  auto-update-status: "4000"