server:
  port: 8088
  servlet:
    context-path: /sockets

spring:
  application:
    name: socket-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/socket-service?authSource=admin
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      connect-timeout: 5000
      timeout: 5000
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: true
        delivery.timeout.ms: 120000
        linger.ms: 1
        request.timeout.ms: 30000
    consumer:
      group-id: socket-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.json.trusted.packages: "*"
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate

jwt:
  signerKey: ${JWT_SIGNER_KEY}

app:
  services:
    chat:
      url: ${CHAT_SERVICE_URL}
    profile:
      url: ${PROFILE_SERVICE_URL}
    identity:
      url: ${IDENTITY_SERVICE_URL}

resilience4j:
  circuitbreaker:
    instances:
      socketIdentityService:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      socketProfileService:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  ratelimiter:
    instances:
      socketIdentityService:
        limit-for-period: 20
        limit-refresh-period: 1s
        timeout-duration: 0s
      socketProfileService:
        limit-for-period: 80
        limit-refresh-period: 1s
        timeout-duration: 0s
  retry:
    instances:
      socketIdentityService:
        max-attempts: 2
        wait-duration: 500ms
      socketProfileService:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2