server:
  port: 8084
  servlet:
    context-path: /file

spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:${MONGODB_ROOT_PASSWORD:REDACTED_LEGACY_CREDENTIAL}@localhost:27017/file-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 7MB

jwt:
  signerKey: ${JWT_SIGNER_KEY:uahkQQArjCd/s458SRMXBYTBbV8FiePF7TPREMKeRijTgiD6DOkEdtmxtcGPVGP0}

app:
  file:
    storage-dir: D:/Video
    download-prefix: http://localhost:8888/api/v1/file/media/download/