server:
  port: 8081
  servlet:
    context-path: /profiles

jwt:
  signerKey: ${JWT_SIGNER_KEY}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: false
    mongodb:
      uri: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/profile-service?authSource=admin

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: true
        delivery.timeout.ms: 120000
        linger.ms: 1
        request.timeout.ms: 30000
    consumer:
      group-id: profile-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: manual_immediate
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 2.0

  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      postService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      friendService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

  timeout:
    instances:
      postService:
        timeout-duration: 2s
      friendService:
        timeout-duration: 2s

app:
  services:
    file:
      url: ${FILE_SERVICE_URL}
    post:
      url: ${POST_SERVICE_URL}
    friend:
      url: ${FRIEND_SERVICE_URL}
    notification:
      url: ${NOTIFICATION_SERVICE_URL}