server:
  port: 8081
  servlet:
    context-path: /profile

jwt:
  signerKey: ${JWT_SIGNER_KEY}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
  neo4j:
    uri: bolt://${NEO4J_HOST}:7687
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

app:
  services:
    file:
      url: "http://localhost:8084/file"