param(
    [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
    [switch]$SkipComposeDatabaseMigration,
    [switch]$RecoverMySqlToCurrentEnv
)

$ErrorActionPreference = 'Stop'

function New-RandomSecret([int]$ByteCount) {
    $bytes = New-Object byte[] $ByteCount
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($bytes)
    }
    finally {
        $rng.Dispose()
    }

    return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

function Read-DotEnv([string]$Path) {
    $values = @{}
    foreach ($line in Get-Content -LiteralPath $Path -Encoding UTF8) {
        if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$') {
            $values[$Matches[1]] = $Matches[2]
        }
    }
    return $values
}

function Write-DotEnvUpdates([string]$Path, [System.Collections.IDictionary]$Updates) {
    $lines = [System.Collections.Generic.List[string]]::new()
    $seen = @{}

    foreach ($line in Get-Content -LiteralPath $Path -Encoding UTF8) {
        if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=') {
            $key = $Matches[1]
            if ($Updates.Contains($key)) {
                $lines.Add("$key=$($Updates[$key])")
                $seen[$key] = $true
                continue
            }
        }
        $lines.Add($line)
    }

    $missing = @($Updates.Keys | Where-Object { -not $seen.ContainsKey($_) })
    if ($missing.Count -gt 0) {
        $lines.Add('')
        $lines.Add('# Local credentials generated by scripts/rotate-local-secrets.ps1')
        foreach ($key in $missing) {
            $lines.Add("$key=$($Updates[$key])")
        }
    }

    $utf8NoBom = [System.Text.UTF8Encoding]::new($false)
    $temporaryPath = "$Path.rotating"
    [System.IO.File]::WriteAllLines($temporaryPath, $lines, $utf8NoBom)
    Move-Item -LiteralPath $temporaryPath -Destination $Path -Force
}

function Escape-SqlLiteral([string]$Value) {
    return $Value.Replace("'", "''")
}

function Wait-ForCommand([scriptblock]$Probe, [string]$Description, [int]$Attempts = 60) {
    for ($attempt = 1; $attempt -le $Attempts; $attempt++) {
        $previousErrorActionPreference = $ErrorActionPreference
        $ErrorActionPreference = 'Continue'
        try {
            & $Probe *> $null
            $probeSucceeded = $LASTEXITCODE -eq 0
        }
        finally {
            $ErrorActionPreference = $previousErrorActionPreference
        }
        if ($probeSucceeded) {
            return
        }
        Start-Sleep -Seconds 2
    }
    throw "Timed out waiting for $Description"
}

function Restore-ProcessEnvironment([string]$Name, $PreviousValue) {
    if ($null -eq $PreviousValue) {
        Remove-Item "Env:$Name" -ErrorAction SilentlyContinue
    }
    else {
        Set-Item "Env:$Name" $PreviousValue
    }
}

$envPath = Join-Path $ProjectRoot '.env'

if (-not (Test-Path -LiteralPath $envPath)) {
    throw "Missing local environment file: $envPath"
}

$current = Read-DotEnv $envPath
$requiredExisting = @(
    'MYSQL_ROOT_USERNAME',
    'MYSQL_ROOT_PASSWORD',
    'MONGODB_ROOT_USERNAME',
    'MONGODB_ROOT_PASSWORD',
    'MONGODB_REPLICA_SET_KEY'
)
foreach ($key in $requiredExisting) {
    if (-not $current.ContainsKey($key) -or [string]::IsNullOrWhiteSpace($current[$key])) {
        throw "Cannot rotate local credentials because $key is missing from .env"
    }
}

if ($RecoverMySqlToCurrentEnv) {
    Push-Location $ProjectRoot
    try {
        $mysqlContainer = $current['MYSQL_CONTAINER_NAME']
        if ([string]::IsNullOrWhiteSpace($mysqlContainer)) { $mysqlContainer = 'mysql' }
        & docker stop $mysqlContainer 2>$null | Out-Host

        $mysqlVolume = @(& docker volume ls --filter 'label=com.docker.compose.project=project' --filter 'label=com.docker.compose.volume=mysql_data' --format '{{.Name}}') | Select-Object -First 1
        if ([string]::IsNullOrWhiteSpace($mysqlVolume)) {
            throw 'Could not find the Compose MySQL data volume'
        }

        $recoveryContainer = 'mysql-credential-recovery'
        & docker rm -f $recoveryContainer 2>$null | Out-Null
        & docker run --detach --rm --name $recoveryContainer --mount "source=$mysqlVolume,target=/var/lib/mysql" $current['MYSQL_IMAGE'] --skip-grant-tables --skip-networking=0 | Out-Null
        if ($LASTEXITCODE -ne 0) { throw 'Unable to start MySQL recovery container' }

        try {
            Wait-ForCommand {
                & docker exec $recoveryContainer mysqladmin ping -uroot --silent 2>$null
            } 'MySQL recovery mode'

            $rootUser = Escape-SqlLiteral $current['MYSQL_ROOT_USERNAME']
            $rootPassword = Escape-SqlLiteral $current['MYSQL_ROOT_PASSWORD']
            $recoverySql = @"
FLUSH PRIVILEGES;
ALTER USER '$rootUser'@'localhost' IDENTIFIED BY '$rootPassword';
CREATE USER IF NOT EXISTS '$rootUser'@'%' IDENTIFIED BY '$rootPassword';
ALTER USER '$rootUser'@'%' IDENTIFIED BY '$rootPassword';
FLUSH PRIVILEGES;
"@
            $recoverySql | & docker exec -i $recoveryContainer mysql -uroot
            if ($LASTEXITCODE -ne 0) { throw 'Unable to restore the MySQL root credential from .env' }
            Write-Host 'MySQL root credential restored to the current ignored .env value.'
        }
        finally {
            & docker stop $recoveryContainer 2>$null | Out-Null
        }
    }
    finally {
        Pop-Location
    }
    return
}

# Keep a local, ignored recovery record before mutating persisted database
# users. If the process is interrupted, the new values are still recoverable.
$pendingRotationPath = Join-Path $ProjectRoot '.env.rotation-pending'
$rotationKeys = @(
    'MYSQL_ROOT_PASSWORD',
    'MONGODB_ROOT_PASSWORD',
    'MONGODB_REPLICA_SET_KEY',
    'DEBEZIUM_DB_USERNAME',
    'DEBEZIUM_DB_PASSWORD',
    'REDIS_PASSWORD',
    'ELASTICSEARCH_PASSWORD',
    'JWT_SIGNER_KEY',
    'BOOTSTRAP_ADMIN_USERNAME',
    'BOOTSTRAP_ADMIN_EMAIL',
    'BOOTSTRAP_ADMIN_PASSWORD'
)

if (Test-Path -LiteralPath $pendingRotationPath) {
    Write-Host 'Resuming the existing pending credential rotation.'
    $pending = Read-DotEnv $pendingRotationPath
    $rotated = [ordered]@{}
    foreach ($key in $rotationKeys) {
        if (-not $pending.ContainsKey($key) -or [string]::IsNullOrWhiteSpace($pending[$key])) {
            throw "Pending rotation file is missing $key"
        }
        $rotated[$key] = $pending[$key]
    }
}
else {
    $rotated = [ordered]@{
        MYSQL_ROOT_PASSWORD       = New-RandomSecret 36
        MONGODB_ROOT_PASSWORD     = New-RandomSecret 36
        MONGODB_REPLICA_SET_KEY   = ''
        DEBEZIUM_DB_USERNAME      = 'debezium'
        DEBEZIUM_DB_PASSWORD      = New-RandomSecret 36
        REDIS_PASSWORD            = New-RandomSecret 36
        ELASTICSEARCH_PASSWORD    = New-RandomSecret 36
        JWT_SIGNER_KEY            = New-RandomSecret 64
        BOOTSTRAP_ADMIN_USERNAME  = if ($current['BOOTSTRAP_ADMIN_USERNAME']) { $current['BOOTSTRAP_ADMIN_USERNAME'] } else { 'admin' }
        BOOTSTRAP_ADMIN_EMAIL     = if ($current['BOOTSTRAP_ADMIN_EMAIL']) { $current['BOOTSTRAP_ADMIN_EMAIL'] } else { 'admin@example.invalid' }
        BOOTSTRAP_ADMIN_PASSWORD  = New-RandomSecret 36
    }

    # MongoDB requires a long base64 keyFile value.
    $mongoKeyBytes = New-Object byte[] 756
    $mongoKeyRng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $mongoKeyRng.GetBytes($mongoKeyBytes)
    }
    finally {
        $mongoKeyRng.Dispose()
    }
    $rotated['MONGODB_REPLICA_SET_KEY'] = [Convert]::ToBase64String($mongoKeyBytes)

    $pendingLines = [System.Collections.Generic.List[string]]::new()
    foreach ($key in $rotated.Keys) {
        $pendingLines.Add("$key=$($rotated[$key])")
    }
    $utf8NoBom = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllLines($pendingRotationPath, $pendingLines, $utf8NoBom)
}
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

Push-Location $ProjectRoot
try {
    if (-not $SkipComposeDatabaseMigration) {
        $oldDbzUsernameEnvironment = $env:DEBEZIUM_DB_USERNAME
        $oldDbzPasswordEnvironment = $env:DEBEZIUM_DB_PASSWORD
        $env:DEBEZIUM_DB_USERNAME = $rotated['DEBEZIUM_DB_USERNAME']
        $env:DEBEZIUM_DB_PASSWORD = $rotated['DEBEZIUM_DB_PASSWORD']

        try {
            Write-Host 'Starting MySQL only to rotate persisted database credentials...'
            & docker compose up -d mysql
            if ($LASTEXITCODE -ne 0) { throw 'Unable to start MySQL for credential rotation' }

            $mysqlContainer = $current['MYSQL_CONTAINER_NAME']
            if ([string]::IsNullOrWhiteSpace($mysqlContainer)) { $mysqlContainer = 'mysql' }
            $mysqlRootUsername = $current['MYSQL_ROOT_USERNAME']
            Wait-ForCommand {
                & docker exec $mysqlContainer mysqladmin ping --silent
            } 'MySQL'

            $mysqlAuthPassword = $null
            foreach ($candidate in @($current['MYSQL_ROOT_PASSWORD'], $rotated['MYSQL_ROOT_PASSWORD']) | Select-Object -Unique) {
                $previousErrorActionPreference = $ErrorActionPreference
                $ErrorActionPreference = 'Continue'
                try {
                    & docker exec -e "MYSQL_PWD=$candidate" $mysqlContainer mysql "-u$mysqlRootUsername" --batch --skip-column-names --execute 'SELECT 1' *> $null
                    if ($LASTEXITCODE -eq 0) { $mysqlAuthPassword = $candidate; break }
                }
                finally {
                    $ErrorActionPreference = $previousErrorActionPreference
                }
            }
            if ($null -eq $mysqlAuthPassword) { throw 'Neither current nor pending MySQL root credential is valid' }

            $rootUser = Escape-SqlLiteral $mysqlRootUsername
            $newRootPassword = Escape-SqlLiteral $rotated['MYSQL_ROOT_PASSWORD']
            $dbzUser = Escape-SqlLiteral $rotated['DEBEZIUM_DB_USERNAME']
            $dbzPassword = Escape-SqlLiteral $rotated['DEBEZIUM_DB_PASSWORD']
            # dbzUser is created/altered with mysql_native_password (not MySQL 8's
            # default caching_sha2_password): the Debezium JDBC driver refuses RSA
            # public-key retrieval over a non-SSL connection, so a cold auth cache
            # makes caching_sha2_password fail with a misleading "Access denied"
            # even when the password is correct.
            $mysqlRotationSql = @"
ALTER USER '$rootUser'@'localhost' IDENTIFIED BY '$newRootPassword';
CREATE USER IF NOT EXISTS '$rootUser'@'%' IDENTIFIED BY '$newRootPassword';
ALTER USER '$rootUser'@'%' IDENTIFIED BY '$newRootPassword';
CREATE USER IF NOT EXISTS '$dbzUser'@'%' IDENTIFIED WITH mysql_native_password BY '$dbzPassword';
ALTER USER '$dbzUser'@'%' IDENTIFIED WITH mysql_native_password BY '$dbzPassword';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '$dbzUser'@'%';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT, LOCK TABLES ON *.* TO '$dbzUser'@'%';
FLUSH PRIVILEGES;
"@
            $mysqlRotationSql | & docker exec -i -e "MYSQL_PWD=$mysqlAuthPassword" $mysqlContainer mysql "-u$mysqlRootUsername"
            if ($LASTEXITCODE -ne 0) { throw 'MySQL credential rotation failed' }
            & docker compose stop mysql | Out-Host
            if ($LASTEXITCODE -ne 0) { throw 'Unable to stop MySQL after credential rotation' }

            Write-Host 'Starting MongoDB only to rotate persisted database credentials...'
            & docker compose up -d mongodb
            if ($LASTEXITCODE -ne 0) { throw 'Unable to start MongoDB for credential rotation' }

            $mongoContainer = $current['MONGODB_CONTAINER_NAME']
            if ([string]::IsNullOrWhiteSpace($mongoContainer)) { $mongoContainer = 'mongodb' }
            $mongoRootUsername = $current['MONGODB_ROOT_USERNAME']
            Wait-ForCommand {
                & docker exec $mongoContainer mongosh --quiet --eval 'quit(0)'
            } 'MongoDB'

            $mongoAuthPassword = $null
            foreach ($candidate in @($current['MONGODB_ROOT_PASSWORD'], $rotated['MONGODB_ROOT_PASSWORD']) | Select-Object -Unique) {
                $previousErrorActionPreference = $ErrorActionPreference
                $ErrorActionPreference = 'Continue'
                try {
                    & docker exec $mongoContainer mongosh --quiet --username $mongoRootUsername --password $candidate --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 }).ok' *> $null
                    if ($LASTEXITCODE -eq 0) { $mongoAuthPassword = $candidate; break }
                }
                finally {
                    $ErrorActionPreference = $previousErrorActionPreference
                }
            }
            if ($null -eq $mongoAuthPassword) { throw 'Neither current nor pending MongoDB root credential is valid' }

            $newMongoPasswordJson = $rotated['MONGODB_ROOT_PASSWORD'] | ConvertTo-Json -Compress
            $dbzUserJson = $rotated['DEBEZIUM_DB_USERNAME'] | ConvertTo-Json -Compress
            $dbzPasswordJson = $rotated['DEBEZIUM_DB_PASSWORD'] | ConvertTo-Json -Compress
            $mongoRotationJs = @"
const adminDb = db.getSiblingDB('admin');
const rootUser = process.env.MONGODB_ROOT_USERNAME;
const newRootPassword = $newMongoPasswordJson;
const dbzUser = $dbzUserJson;
const dbzPassword = $dbzPasswordJson;
const dbzRoles = [
  { role: 'readAnyDatabase', db: 'admin' },
  { role: 'clusterMonitor', db: 'admin' },
  { role: 'read', db: 'local' }
];
const existingDbz = adminDb.getUser(dbzUser);
if (existingDbz) {
  adminDb.updateUser(dbzUser, { pwd: dbzPassword, roles: dbzRoles });
} else {
  adminDb.createUser({ user: dbzUser, pwd: dbzPassword, roles: dbzRoles });
}
adminDb.updateUser(rootUser, { pwd: newRootPassword });
"@
            $mongoRotationJs | & docker exec -i $mongoContainer mongosh --quiet --username $mongoRootUsername --password $mongoAuthPassword --authenticationDatabase admin
            if ($LASTEXITCODE -ne 0) { throw 'MongoDB credential rotation failed' }
            & docker compose stop mongodb | Out-Host
            if ($LASTEXITCODE -ne 0) { throw 'Unable to stop MongoDB after credential rotation' }
        }
        catch {
            $previousErrorActionPreference = $ErrorActionPreference
            $ErrorActionPreference = 'Continue'
            try { & docker compose stop mysql mongodb *> $null }
            finally { $ErrorActionPreference = $previousErrorActionPreference }
            Write-Warning "Credential rotation did not finish. Recovery values remain in $pendingRotationPath"
            throw
        }
        finally {
            Restore-ProcessEnvironment 'DEBEZIUM_DB_USERNAME' $oldDbzUsernameEnvironment
            Restore-ProcessEnvironment 'DEBEZIUM_DB_PASSWORD' $oldDbzPasswordEnvironment
        }
    }

    Write-DotEnvUpdates $envPath $rotated
    Remove-Item -LiteralPath $pendingRotationPath -Force

    Write-Host 'Rotated local credentials without printing secret values:'
    $rotated.Keys | ForEach-Object { Write-Host "  - $_" }
    Write-Warning 'Google OAuth, Brevo and Backblaze credentials were copied unchanged. Revoke and recreate them in each provider dashboard.'
}
finally {
    Pop-Location
}
