server:
  port: 8087
  servlet:
    context-path: /friends

spring:
  application:
    name: friends-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/friend-service}
    username: ${DBMS_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:REDACTED_LEGACY_CREDENTIAL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: friend-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
jwt:
  signerKey: ${JWT_SIGNER_KEY:uahkQQArjCd/s458SRMXBYTBbV8FiePF7TPREMKeRijTgiD6DOkEdtmxtcGPVGP0}

app:
  services:
    profile:
      url: "http://localhost:8081/profile"


