server:
  port: 9000

spring:
  application:
    name: debezium-manager
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

app:
  services:
    debezium:
      connect-url: ${DEBEZIUM_CONNECT_URL}